apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    infra_id: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
    revision_id: 8fbb8776-c29f-494e-8eaa-aaf53deffa21
    subject: '{{workflow.parameters.appNamespace}}_kube-proxy'
    workflow_id: cb7b8b10-0842-487c-9280-654eedb5c7ae
    workflows.argoproj.io/controller-instanceid: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
  name: abcd
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
    - name: appNamespace
      value: kube-system
  entrypoint: argowf-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: argowf-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-faults
        template: install-chaos-faults
    - - arguments: {}
        name: pod-delete-9i8
        template: pod-delete-9i8
    - - arguments: {}
        name: cleanup-chaos-resources
        template: cleanup-chaos-resources
  - container:
      args:
      - kubectl apply -f /tmp/pod-delete.yaml -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: install-chaos-faults
        path: /tmp/pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes a pod belonging to a deployment/statefulset/daemonset
            kind: ChaosExperiment
            metadata:
              name: pod-delete
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - "apps"
                      - "batch"
                      - "litmuschaos.io"
                    resources:
                      - "deployments"
                      - "jobs"
                      - "pods"
                      - "pods/log"
                      - "events"
                      - "configmaps"
                      - "chaosengines"
                      - "chaosexperiments"
                      - "chaosresults"
                    verbs:
                      - "create"
                      - "list"
                      - "get"
                      - "patch"
                      - "update"
                      - "delete"
                  - apiGroups:
                      - ""
                    resources:
                      - "nodes"
                    verbs:
                      - "get"
                      - "list"
                image: "litmuschaos.docker.scarf.sh/litmuschaos/go-runner:latest"
                imagePullPolicy: Always
                args:
                - -c
                - ./experiments -name pod-delete
                command:
                - /bin/bash
                env:

                - name: TOTAL_CHAOS_DURATION
                  value: '15'

                # Period to wait before and after injection of chaos in sec
                - name: RAMP_TIME
                  value: ''

                # provide the kill count
                - name: KILL_COUNT
                  value: ''

                - name: FORCE
                  value: 'true'

                - name: CHAOS_INTERVAL
                  value: '5'

                labels:
                  name: pod-delete
    metadata: {}
    name: install-chaos-faults
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: cleanup-chaos-resources
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-pod-delete-9i8.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/litmuschaos/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete-9i8
        path: /tmp/chaosengine-pod-delete-9i8.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                workflow_run_id: "{{ workflow.uid }}"
                workflow_name: abcd
              annotations:
                probeRef: '[{"name":"nginx-health-check","mode":"Continuous"}]'
              generateName: pod-delete-9i8
            spec:
              appinfo:
                appns: ""
                applabel: ""
                appkind: ""
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "15"
                        - name: RAMP_TIME
                          value: ""
                        - name: FORCE
                          value: "true"
                        - name: CHAOS_INTERVAL
                          value: "5"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                        - name: TARGET_CONTAINER
                          value: ""
                        - name: TARGET_PODS
                          value: ""
                        - name: DEFAULT_HEALTH_CHECK
                          value: "false"
                        - name: NODE_LABEL
                          value: ""
                        - name: SEQUENCE
                          value: parallel
    metadata:
      labels:
        weight: "10"
    name: pod-delete-9i8
    outputs: {}
status:
  finishedAt: null
  startedAt: null
