apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    infra_id: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
    revision_id: e0388ca8-cba4-4548-b0c9-dd7ca98045a1
    workflow_id: 07d4bf98-15fd-4b57-a9f6-321500899511
    workflows.argoproj.io/controller-instanceid: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
  name: gcp-chaos-test
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: gcp-chaos-test
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: gcp-chaos-test
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-faults
        template: install-chaos-faults
    - - arguments: {}
        name: gcp-vm-instance-stop-93q
        template: gcp-vm-instance-stop-93q
    - - arguments: {}
        name: cleanup-chaos-resources
        template: cleanup-chaos-resources
  - container:
      args:
      - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}} && sleep
        30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: gcp-vm-instance-stop-93q
        path: /tmp/gcp-vm-instance-stop-93q.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: >
                Stops GCP VM instances and GKE nodes for a specified duration and later
                restarts them
            kind: ChaosExperiment
            metadata:
              name: gcp-vm-instance-stop
              labels:
                name: gcp-vm-instance-stop
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 3.16.0
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.16.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name gcp-vm-instance-stop
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: SEQUENCE
                    value: parallel
                  - name: RAMP_TIME
                    value: ""
                  - name: MANAGED_INSTANCE_GROUP
                    value: disable
                  - name: VM_INSTANCE_NAMES
                    value: ""
                  - name: GCP_PROJECT_ID
                    value: ""
                  - name: ZONES
                    value: ""
                  - name: DEFAULT_HEALTH_CHECK
                    value: "false"
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: gcp-vm-instance-stop
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 3.16.0
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-faults
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.11.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: cleanup-chaos-resources
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-gcp-vm-instance-stop-93q.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/litmuschaos/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: gcp-vm-instance-stop-93q
        path: /tmp/chaosengine-gcp-vm-instance-stop-93q.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                workflow_run_id: "{{ workflow.uid }}"
                workflow_name: gcp-chaos-test
              annotations:
                probeRef: '[{"name":"check-frontend-access-url-NSC0nrejQmSIC0_rya0Plw","mode":"SOT"}]'
              generateName: gcp-vm-instance-stop-93q
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: gcp-vm-instance-stop
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: SEQUENCE
                          value: parallel
                        - name: RAMP_TIME
                          value: ""
                        - name: MANAGED_INSTANCE_GROUP
                          value: disable
                        - name: VM_INSTANCE_NAMES
                          value: ""
                        - name: GCP_PROJECT_ID
                          value: ""
                        - name: ZONES
                          value: ""
                        - name: DEFAULT_HEALTH_CHECK
                          value: "false"
    metadata:
      labels:
        weight: "10"
    name: gcp-vm-instance-stop-93q
    outputs: {}
status:
  finishedAt: null
  startedAt: null
