apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    infra_id: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
    revision_id: 2de28ece-9f21-49f3-a121-e14c53fc6fb0
    workflow_id: 07d4bf98-15fd-4b57-a9f6-321500899511
    workflows.argoproj.io/controller-instanceid: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
  name: gcp-chaos-test
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: gcp-chaos-test
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: gcp-chaos-test
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-faults
        template: install-chaos-faults
    - - arguments: {}
        name: gcp-vm-process-kill-4nj
        template: gcp-vm-process-kill-4nj
    - - arguments: {}
        name: cleanup-chaos-resources
        template: cleanup-chaos-resources
  - container:
      args:
      - kubectl apply -f /tmp/ -n {{workflow.parameters.adminModeNamespace}} && sleep
        30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: gcp-vm-process-kill-4nj
        path: /tmp/gcp-vm-process-kill-4nj.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Kills specified processes on GCP VM instances for a specified duration
            kind: ChaosExperiment
            metadata:
              name: gcp-vm-process-kill
              labels:
                name: gcp-vm-process-kill
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: ci
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                    resources:
                      - pods
                    verbs:
                      - create
                      - delete
                      - get
                      - list
                      - patch
                      - update
                      - deletecollection
                  - apiGroups:
                      - ""
                    resources:
                      - events
                    verbs:
                      - create
                      - get
                      - list
                      - patch
                      - update
                  - apiGroups:
                      - ""
                    resources:
                      - secrets
                      - configmaps
                    verbs:
                      - get
                      - list
                  - apiGroups:
                      - ""
                    resources:
                      - pods/log
                    verbs:
                      - get
                      - list
                      - watch
                  - apiGroups:
                      - batch
                    resources:
                      - jobs
                    verbs:
                      - create
                      - list
                      - get
                      - delete
                      - deletecollection
                  - apiGroups:
                      - litmuschaos.io
                    resources:
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: litmuschaos.docker.scarf.sh/litmuschaos/go-runner:latest
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name gcp-vm-process-kill
                command:
                  - /bin/bash
                env:
                  - name: PROCESS_NAME
                    value: ""
                  - name: SIGNAL
                    value: "9"
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: GCP_PROJECT_ID
                    value: ""
                  - name: INSTANCE_NAME
                    value: ""
                  - name: ZONE_NAME
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                  - name: DEFAULT_HEALTH_CHECK
                    value: "false"
                labels:
                  name: gcp-vm-process-kill
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: ci
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
                auxiliaryAppInfo: ""
                statusCheckTimeouts:
                  delay: 2
                  timeout: 180
    metadata: {}
    name: install-chaos-faults
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:2.11.0
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: cleanup-chaos-resources
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-gcp-vm-process-kill-4nj.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/litmuschaos/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: gcp-vm-process-kill-4nj
        path: /tmp/chaosengine-gcp-vm-process-kill-4nj.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                workflow_run_id: "{{ workflow.uid }}"
                workflow_name: gcp-chaos-test
              annotations:
                probeRef: '[{"name":"nginx-health-check","mode":"SOT"}]'
              generateName: gcp-vm-process-kill-4nj
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: gcp-vm-process-kill
                  spec:
                    components:
                      env:
                        - name: PROCESS_NAME
                          value: prometheus
                        - name: SIGNAL
                          value: "9"
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: RAMP_TIME
                          value: ""
                        - name: GCP_PROJECT_ID
                          value: ""
                        - name: INSTANCE_NAME
                          value: ""
                        - name: ZONE_NAME
                          value: ""
                        - name: SEQUENCE
                          value: parallel
                        - name: DEFAULT_HEALTH_CHECK
                          value: "false"
    metadata:
      labels:
        weight: "10"
    name: gcp-vm-process-kill-4nj
    outputs: {}
status:
  finishedAt: null
  startedAt: null
