apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    infra_id: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
    revision_id: bfe242c6-02b2-4635-9c0d-0c60a2e7f08f
    subject: '{{workflow.parameters.appNamespace}}_kube-proxy'
    workflow_id: 0b86add8-f0d5-4d76-819a-8ca67f55ee25
    workflows.argoproj.io/controller-instanceid: 446420e7-e7fa-4af7-b7e3-97dbde7e0114
  name: test-retain
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
    - name: appNamespace
      value: kube-system
  entrypoint: argowf-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - inputs: {}
    metadata: {}
    name: argowf-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-faults
        template: install-chaos-faults
    - - arguments: {}
        name: run-chaos
        template: run-chaos
    - - arguments: {}
        name: cleanup-chaos-resources
        template: cleanup-chaos-resources
  - container:
      args:
      - kubectl apply -f /tmp/pod-cpu-hog.yaml -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: install-chaos-faults
        path: /tmp/pod-cpu-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects cpu consumption on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-cpu-hog
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - "batch"
                      - "litmuschaos.io"
                    resources:
                      - "jobs"
                      - "pods"
                      - "pods/log"
                      - "events"
                      - "chaosengines"
                      - "chaosexperiments"
                      - "chaosresults"
                    verbs:
                      - "create"
                      - "list"
                      - "get"
                      - "patch"
                      - "update"
                      - "delete"
                image: "litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.16.0"
                imagePullPolicy: Always
                args:
                - -c
                - ./experiments -name pod-cpu-hog
                command:
                - /bin/bash
                env:
                - name: TOTAL_CHAOS_DURATION
                  value: '30'

                - name: CHAOS_INTERVAL
                  value: '10'

                ## Number of CPU cores to stress
                - name: CPU_CORES
                  value: '1'

                ## Percentage of total pods to target
                - name: PODS_AFFECTED_PERC
                  value: ''

                ## Period to wait before and after injection of chaos in sec
                - name: RAMP_TIME
                  value: ''

                - name: TARGET_POD
                  value: ''

                labels:
                  name: pod-cpu-hog
    metadata: {}
    name: install-chaos-faults
    outputs: {}
  - container:
      args:
      - -file=/tmp/chaosengine-run-chaos.yaml
      - -saveName=/tmp/engine-name
      image: docker.io/litmuschaos/litmus-checker:2.11.0
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: run-chaos
        path: /tmp/chaosengine-run-chaos.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              labels:
                context: "{{workflow.parameters.appNamespace}}_kube-proxy"
                workflow_run_id: "{{ workflow.uid }}"
                workflow_name: test-retain
              annotations:
                probeRef: '[{"name":"nginx-health-check","mode":"SOT"}]'
              generateName: run-chaos
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: retain
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-cpu-hog
                  spec:
                    components:
                      env:
                        - name: TARGET_CONTAINER
                          value: kube-proxy
                        - name: CPU_CORES
                          value: "1"
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: CHAOS_KILL_COMMAND
                          value: >-
                            kill -9 $(ps afx | grep "[md5sum] /dev/zero" | awk '{print$1}' |
                            tr '

                            ' ' ')
    metadata:
      labels:
        weight: "10"
    name: run-chaos
    outputs: {}
  - container:
      args:
      - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: cleanup-chaos-resources
    outputs: {}
status:
  finishedAt: null
  startedAt: null
